version: '3'
services:
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#       - "15672:15672"
#       - "5672:5672"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=teauser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=teadb